Qriosity/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
import user
import home

urlpatterns = [
    path('harrypotter/', admin.site.urls),
    path('user/', include('user.urls')),
    path('quiz/', include('quiz.urls')),
    path('', include('home.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'


urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('rules/', views.rules, name="rules"),
    path('abadakadabra/qualifiedlist/', views.page, name="page"),
]

quiz/urls.py
from django.urls import path
from django.conf.urls import url,include
from . import views

app_name = 'quiz'


urlpatterns = [
    path('', views.StageOne, name='stageone'),
    path('answer/', views.Stage1Answer, name="answer"),
    path('hint/', views.Stage1Hint, name="hint"),
    path('stage2/', views.Index, name="index"),
    path('<int:qid>', views.Individual, name="individual"),
    path('passcode/', views.Passcode, name="passcode"),
    path('algo/', views.Algo, name="algo"),
    
    url(r'^algo/questions/(?P<pk>.*)/$',views.showanswer,name='showanswer'),
]

user/urls.py
from django.urls import path
from .import views

app_name = 'user'


urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('privacypolicy', views.privacy_policy_fb, name="privacypolicy"),
    path('details/', views.UserData, name="details"),
    path('form/', views.Formdata, name="formdata"),
    path('details/logout/', views.logout, name="logout"),
    path('story/', views.story, name="story"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
# Create your models here.


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=400)
    email = models.CharField(max_length=100, null=True, blank=True)
    image = models.CharField(max_length=200, blank=True)
    score = models.IntegerField(default=0)
    rank = models.IntegerField(default=0)
    last_submit = models.DateTimeField(
        default=datetime.utcnow()+timedelta(hours=5.5))
    question_level = models.IntegerField(default=1)
    level2 = models.IntegerField(default=-2)
    count2 = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class PlayerDetails(models.Model):
    user_name = models.OneToOneField(
        Player, on_delete=models.CASCADE, primary_key=True)
    full_name = models.CharField(default="your name", max_length=400)
    college = models.CharField(default="none", max_length=400)
    year = models.CharField(default="1", max_length=10)
    contact = models.BigIntegerField(default=1, blank=True)

    def __str__(self):
        return self.college


class Solved(models.Model):
    gamer = models.ForeignKey(Player, on_delete=models.CASCADE)
    level_on = models.IntegerField(default=0, blank=True)
    solved = models.BooleanField(default=False)


class StageOneHint(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    level = models.IntegerField(default=0, blank=True)
    taken = models.BooleanField(default=False)

user/forms.py
from django import forms


class UserDetails(forms.Form):
    full_name = forms.CharField(max_length=400, label="Enter Your Full Name")
    college = forms.CharField(max_length=400, label="Enter Your college name")
    year = forms.IntegerField(min_value=1, max_value=4,
                              label="Enter your studying year")
    contact = forms.CharField(
        min_length=10, max_length=10, label="Enter your Phone Number", required=False)

user/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.contrib.auth.decorators import login_required
from .import models
from datetime import datetime, timedelta
from .forms import UserDetails
# from django.contrib.auth.models import User

# Create your views here.

current_leaderboard = None


def logout(request):
    return render(request, 'user/logout.html')


@login_required(login_url='/login', redirect_field_name=None)
def dashboard(request):
    player = models.Player.objects.get(user=request.user)
    print("In dashboard - Name - {}  User - {}".format(player.name, player.user))
    cl = models.Player.objects.order_by(
        '-score', 'last_submit')
    j = 0

    # code for calaculating the dyanmic rank 
    # cl gives the scores in descending order 
    # we store the rank in j
    # variable naming is very bad XD

    for i in cl:
        j += 1
        if i.user == player.user:
            print(j)
            break


    # cl = models.Player.objects.filter(level2__gte=0).order_by(
    #     '-score', 'last_submit')
    # j = 0
    # for i in cl:
    #     j += 1
    #     if i.user == player.user:
    #         print(j)
    #         break
    # if player.level2 < 0:
    #     j = 0
    return render(request, 'user/dashboard.html', {'player': player, "rank": j})


#@login_required(login_url='/login', redirect_field_name=None)
def save_profile(backend, user, response, *args, **kwargs):
    if backend.name == 'google-oauth2':
        profile = user
        try:
            player = models.Player.objects.get(user=profile)
        except:
            player = models.Player(user=profile)
            player.last_submit = datetime.utcnow()+timedelta(hours=5.5)
            player.name = response.get('name')
            player.image = response.get('picture')
            player.email = response.get('email')
            player.save()
    elif backend.name == 'facebook':
        profile = user
        try:
            player = models.Player.objects.get(user=profile)
        except:
            player = models.Player(user=profile)
            player.name = response.get(
                'first_name')+" "+response.get('last_name')
            player.email = response.get('email')
            player.image = "http://graph.facebook.com/%s/picture?type=large" \
                % response["id"]
            player.last_submit = datetime.utcnow()+timedelta(hours=5.5)
            player.save()


@login_required(login_url='/login', redirect_field_name=None)
def leaderboard(request):
    global current_leaderboard

    current_leaderboard = models.Player.objects.order_by(
        '-score', 'last_submit')

    leader = models.Player.objects.order_by(
        '-score', 'last_submit')[:1]
    n = models.Player.objects.count()

    # uncomment when 2nd round in play
    # current_leaderboard = models.Player.objects.filter(level2__gte=0).order_by(
    #     '-score', 'last_submit')[:3]
    # leader = models.Player.objects.filter(level2__gte=0).order_by(
    #     '-score', 'last_submit')[:1]
    # n = models.Player.objects.filter(level2__gte=0).count()
    return render(request, 'user/leaderboard.html', {'leaderboard': current_leaderboard, 'leader': leader, 'n': n})


def privacy_policy_fb(request):
    return render(request, "user/privacypolicy.html")


@login_required(login_url='/login', redirect_field_name=None)
def UserData(request):
    my_form = UserDetails()
    context = {
        "form": my_form
    }
    return render(request, "user/details.html", context)


@login_required(login_url='/login', redirect_field_name=None)
def Formdata(request):
    if request.method == "POST":
        my_form = UserDetails(request.POST)
        if my_form.is_valid():
            # my form is valid
            form_data = my_form.cleaned_data
            p1 = models.Player.objects.get(user=request.user)
            r = models.PlayerDetails(
                user_name=p1, college=form_data['college'], year=form_data['year'], contact=form_data['contact'],
                full_name=form_data['full_name'])
            r.save()

        else:
            z = my_form.errors
            print(z)
    p1 = models.Player.objects.get(user=request.user)

    try:
        r = models.PlayerDetails.objects.get(user_name=p1)
        return render(request, 'user/form_status.html', {"details": r})
    except models.PlayerDetails.DoesNotExist:
        render(request, "user/details.html")

    my_form = UserDetails()
    context = {
        "form": my_form
    }
    return render(request, "user/details.html", context)


def story(request):
    return render(request, 'user/story.html')

user/templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> {% block title %}
    <title>Qriosity</title>{% endblock %}
    <link rel="stylesheet" href="{% static 'user/base.css' %}" />
    <link rel="shortcut icon" href="{% static 'user/favicon.ico' %}" />
</head>

<body>
    <div id="particles-js"></div>
    <div class="container">
        <header>
            <h1>
                <a href="{% url 'home:home' %}" class="qriosity">Qriosity 3.0</a>
            </h1>

            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'home:rules'%}">Rules</a>
                    </li>
                    <li>
                        <a href="{% url 'user:leaderboard' %}"> LeaderBoard </a>
                    </li>
                    <li>
                        <a href="{% url 'quiz:stageone' %}">Arena</a>
                    </li>
                    <li>
                        <a href="{% url 'user:story' %}">Story</a>
                    </li>
                    <li>
                        <a href="{% url 'user:dashboard' %}"> Dashboard </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'home:rules'%}">Rules</a>
                    </li>
                    <li>
                        <a href="{% url 'user:leaderboard' %}"> LeaderBoard </a>
                    </li>
                    <li>
                        <a href="{% url 'user:story'%}">Story </a>
                    </li>
                    <li>
                        <a href="{% url 'home:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}{% endblock %}

        <footer>
            <div class="footleft">
                <a href="https://www.ieee.org/" target="_blank" rel="noopener noreferrer">
                    <img src="{% static 'home/ieeembw.png'%}" alt="IEEE" class="ieee" />
                </a>
            </div>
            <div class="contact">
                <div class="ctitle">
                    <b>Contact Us</b>
                </div>

                <div class="clinks">
                    <div class="cinsta">
                        <a href="https://www.instagram.com/ieeesb_nitdgp/" target="_blank" rel="noopener noreferrer">
                            <img src="{% static 'home/insta.png'%}" alt="instagram" />
                        </a>
                    </div>
                    <div class="cfb">
                        <a href="https://www.facebook.com/nitdgpieeesociety/" target="_blank" rel="noopener noreferrer">
                            <img src="{% static 'home/cfb.png'%}" alt="instagram" />
                        </a>
                    </div>
                </div>
            </div>
            <div>
                <div class="footend">
                    <a href="http://www.ieeesbnitdgp.com/" target="_blank" rel="noopener noreferrer">
                        <img src="{% static 'home/ieeew.png'%}" alt="IEEE" class="ieee" />
                    </a>
                </div>
            </div>
        </footer>
    </div>
</body>

</html>