Qriosity/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
import user
import home

urlpatterns = [
    path('harrypotter/', admin.site.urls),
    path('user/', include('user.urls')),
    path('quiz/', include('quiz.urls')),
    path('', include('home.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'


urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('rules/', views.rules, name="rules"),
    path('abadakadabra/qualifiedlist/', views.page, name="page"),
]

quiz/urls.py
from django.urls import path
from django.conf.urls import url,include
from . import views

app_name = 'quiz'


urlpatterns = [
    path('', views.StageOne, name='stageone'),
    path('answer/', views.Stage1Answer, name="answer"),
    path('hint/', views.Stage1Hint, name="hint"),
    path('stage2/', views.Index, name="index"),
    path('<int:qid>', views.Individual, name="individual"),
    path('passcode/', views.Passcode, name="passcode"),
    path('algo/', views.Algo, name="algo"),
    
    url(r'^algo/questions/(?P<pk>.*)/$',views.showanswer,name='showanswer'),
]

user/urls.py
from django.urls import path
from .import views

app_name = 'user'


urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('privacypolicy', views.privacy_policy_fb, name="privacypolicy"),
    path('details/', views.UserData, name="details"),
    path('form/', views.Formdata, name="formdata"),
    path('details/logout/', views.logout, name="logout"),
    path('story/', views.story, name="story"),
]

quiz/models.py
from django.db import models

# Create your models here.

# static questions containing only text and images


class Stage_1(models.Model):
    title = models.CharField(blank=True, max_length=200)
    level = models.IntegerField()
    description = models.TextField(blank=True, default='hello')
    image_url = models.URLField(blank=True)
    hint = models.TextField(blank=True, default='hint')
    answer = models.CharField(blank=True, max_length=400)
    algo = models.TextField(blank=True)

    def __str__(self):
        return str(str(self.level)+str(" . ")+str(self.title))


class StageTwo(models.Model):
    title = models.CharField(blank=True, max_length=200)
    description = models.TextField(blank=True, default='hello')
    answer = models.CharField(blank=True, max_length=400)
    level = models.IntegerField()

    def __str__(self):
        return str(str(self.level)+str(" . ")+str(self.title))

quiz/forms.py
from django import forms


class UserAnswer(forms.Form):
    answer = forms.CharField(
        label="Your Answer Here", required=True)

quiz/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Stage_1, StageTwo
from django.contrib.auth.decorators import login_required
from user.models import Player, Solved, StageOneHint
from .forms import UserAnswer
from datetime import datetime, timedelta
from django.utils import timezone
# Create your views here.

value = False
hintValue = False
hintButton = True
question1 = Stage_1.objects.all()


@login_required(login_url='/login', redirect_field_name=None)
def Algo(request):
    if request.method == "POST":
        player = get_object_or_404(Player, user=request.user)
        n = player.question_level
        if n > Stage_1.objects.count():
            question = Stage_1.objects.order_by('-level')
            return render(request, 'quiz/algorithm.html', {"questions": question})
        else:
            raise Http404("Page does not exist")
    else:
        raise Http404("Page does not exist")


@login_required(login_url='/login', redirect_field_name=None)
def showanswer(request, pk):
    question = get_object_or_404(Stage_1, pk=pk)
    player = get_object_or_404(Player, user=request.user)
    if player.question_level > Stage_1.objects.count():
        return render(request, 'quiz/answerdisplay.html', {'question': question})
    else:
        raise Http404("Page does not exist")


@login_required(login_url='/login', redirect_field_name=None)
def StageOne(request):
    ''' Set the date time as class datetime.datetime
    (year, month, day, hour=0, minute=0, second=0, microsecond=0, tzinfo=None, *, fold=0)'''

    player = get_object_or_404(Player, user=request.user)
    now = datetime.utcnow()+timedelta(hours=5.5)

    


    quiz = datetime(2021, 8, 2, 9, 0, 0)       # Set the Date Time Here
    end = datetime(2021, 9, 2, 23, 0, 0)
    # firstend = datetime(2021, 8, 3, 2, 0, 0)

    print(now)
    if now < quiz:
        print('not time ' + str(quiz))
        return render(request, 'quiz/timer.html')

    # if firstend < now and player.level2 < 0:
    #     return render(request, 'quiz/wait.html')

    if (now > end):
        print('end ' + str(end))
        return render(request, 'quiz/timer.html', {"end": end})

    else:
        print('quiz on')
        if player.level2 < -1:
            player = get_object_or_404(Player, user=request.user)
            question_level = player.question_level

            if player.question_level > Stage_1.objects.count():
                formp = UserAnswer
                check = False
                return render(request, 'quiz/end.html', {"form": formp, "check": check})

            question = get_object_or_404(Stage_1, level=int(question_level))
            my_form = UserAnswer
            hall = player.stageonehint_set.all()
            for i in hall:
                if i.level == question_level:
                    return render(request, 'quiz/Stage1.html', {"question": question, "form": my_form, "value": value, "hint": i.taken})
            player.stageonehint_set.create(
                level=int(question_level), taken=False)
            hint = player.stageonehint_set.get(level=int(question_level))
            return render(request, 'quiz/Stage1.html', {"question": question, "form": my_form, "value": value, "hint": hint.taken})

        if player.level2 == -1:
            return render(request, 'quiz/wait.html')

        if player.level2 > -1:
            q = StageTwo.objects.all()
            player = get_object_or_404(Player, user=request.user)
            if (player.count2 < StageTwo.objects.count()):
                return render(request, 'quiz/index.html', {"q": q, "player": player})
            else:
                return render(request, 'quiz/finish.html', {"player": player})


@login_required(login_url='/login', redirect_field_name=None)
def Stage1Hint(request):
    player = get_object_or_404(Player, user=request.user)
    hint = player.stageonehint_set.get(level=int(player.question_level))
    my_form = UserAnswer
    if hint.taken == True:
        question_level = player.question_level
        question = get_object_or_404(Stage_1, level=int(question_level))
        return render(request, 'quiz/Stage1.html', {"question": question, "form": my_form, "value": value, "hint": hint.taken})
    else:
        player.score -= 5
        hint.taken = True
        hint.save()
        player.save()
        question_level = player.question_level
        question = get_object_or_404(Stage_1, level=int(question_level))
        return render(request, 'quiz/Stage1.html', {"question": question, "form": my_form, "value": value, "hint": hint.taken})


@login_required(login_url='/login', redirect_field_name=None)
def Stage1Answer(request):

    if request.method == "POST":
        player = get_object_or_404(Player, user=request.user)
        question_level = player.question_level

        try:
            question = Stage_1.objects.get(level=int(question_level))
        except Stage_1.DoesNotExist:
            formp = UserAnswer
            check = False
            return render(request, 'quiz/end.html', {"form": formp, "check": check})

        my_form = UserAnswer(request.POST)

        if my_form.is_valid():

            ans = my_form.cleaned_data.get("answer")

            if (str(ans).lower() == str(question.answer).lower()):  # stage one answer checking
                value = False
                player.score += 15
                player.last_submit = timezone.now()
                player.question_level += 1

                player.save()
                question_level = player.question_level
                try:
                    question = Stage_1.objects.get(
                        level=int(question_level))
                except Stage_1.DoesNotExist:
                    formp = UserAnswer
                    check = False
                    return render(request, 'quiz/end.html', {"form": formp, "check": check})

                if player.question_level > Stage_1.objects.count():
                    formp = UserAnswer
                    check = False
                    return render(request, 'quiz/end.html', {"form": formp, "check": check})
                else:
                    my_form1 = UserAnswer
                    player.stageonehint_set.create(
                        level=int(question_level), taken=False)
                    hint = player.stageonehint_set.get(
                        level=int(question_level))
                    if ((question_level) - 1 > 0):
                        try:
                            delobj = player.stageonehint_set.get(
                                level=int(int(question_level)-1))
                        except player.stageonehint_set.DoesNotExist:
                            print("object doesnot exit")
                        else:
                            e = delobj.delete()
                            print(e)

                    return render(request, 'quiz/Stage1.html', {"question": question, "form": my_form1, "value": value, "hint": hint.taken})

            else:
                my_form1 = UserAnswer
                value = True
                hint = player.stageonehint_set.get(
                    level=int(question_level))
                return render(request, 'quiz/Stage1.html', {"question": question, "form": my_form1, "value": value, "hint": hint.taken})
        else:
            return HttpResponse('<h2> Form data not valid</h2>')

    else:
        return HttpResponseNotFound('<h1>Page not found</h1>')


@login_required(login_url='/login', redirect_field_name=None)
def Index(request):
    q = StageTwo.objects.order_by('level')
    player = get_object_or_404(Player, user=request.user)
    if(player.level2 < -1):
        return render(request, 'quiz/smart.html')
    elif(player.level2 == -1):
        return render(request, 'quiz/wait.html')
    else:
        if (player.count2 < StageTwo.objects.count()):
            return render(request, 'quiz/index.html', {"q": q, "player": player})
        else:
            return render(request, 'quiz/finish.html', {"player": player})


@login_required(login_url='/login', redirect_field_name=None)
def Passcode(request):
    code = "ENIGMAHACK"
    if request.method == "POST":
        my_form = UserAnswer(request.POST)
        if my_form.is_valid():
            # print(my_form.cleaned_data)
            ans = my_form.cleaned_data.get("answer")

            if (str(ans).lower() == str(code).lower()):
                player = get_object_or_404(Player, user=request.user)
                player.level2 = -1
                player.score += 60
                player.save()
                question_level = player.question_level
                if ((question_level) - 1 > 0):
                    try:
                        delobj = player.stageonehint_set.get(
                            level=int(int(question_level)-1))
                    except:
                        print("object doesnot exit")
                    else:
                        e = delobj.delete()
                        print(e)
                # print(player.level2)
                q = StageTwo.objects.all()
                player = get_object_or_404(Player, user=request.user)
                return render(request, "quiz/wait.html", {"q": q, "player": player})
            else:
                check = True
                formp = UserAnswer
                return render(request, "quiz/end.html", {"check": check, "form": formp})
        else:
            return HttpResponse("<h1>form data invalid </h1>")


# individual questions of stage 2
@login_required(login_url='/login', redirect_field_name=None)
def Individual(request, qid):
    player = get_object_or_404(Player, user=request.user)
    if(player.level2 < -1):
        return render(request, 'quiz/smart.html')
    elif(player.level2 == -1):
        return render(request, 'quiz/wait.html')
    else:

quiz/templates/quiz/Stage1.html
{% extends 'base.html'%} {% load static %} {% block content %}

<head>
    <link rel="stylesheet" href="{% static 'quiz/quiz.css' %}" />
</head>
<div class="content">
    <div class="stage1 blocks">
        <p>
            Question Level : {{ question.level }}
        </p>

        {% if value %}
        <div class="wrong">
            Wrong Answer!
            <br/> Try Again <br/> 
            {% if hint %} 
            {% else %}
                <div class="warning">
                    Stuck ? Take a Hint. <br /> (You will loose points)
                </div>
            {% endif %}
        </div>
        {% endif %}

        <h3 class="qtitle">{{ question.title }}</h3>

        <!-- description -->
        {% if question.description %}
        <div class="description">{{ question.description }}</div>
        {% endif %}

        <!-- image -->
        {% if question.image %}
        <div>
            <img src="{{ question.image_url }}" alt="{{question.title}}" />
        </div>
        {% endif %}
    </div>

    <div class="anhint blocks">
        {% if hint %}
        <div>
            <h3 class="qtitle">
                You Have Lost 5 points.
            </h3>
        </div>
        <div class="hint">
            <p align="center">
                Hint :
            </p>
            <p align="center" class="ohint">
                {{ question.hint}}
            </p>
        </div>

        {% else %}
        <form action="{% url 'quiz:hint'%}" method="post">
            {% csrf_token %}
            <p>
                Stuck ? Take a Hint. ( You will loose points )
            </p>
            <button type="submit" class="btn">
                Click For Hint
            </button>
        </form>

        {% endif %}

        <form action="{% url 'quiz:answer'%}" method="post">
            {% csrf_token %} {{ form.as_p}}
            <button type="submit" class="btn">
                Submit
            </button>
        </form>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/algorithm.html
{% extends 'base.html'%} {% load static %} {% block content %}
<head>
  <link rel="stylesheet" href="{% static 'quiz/quiz.css' %}" />
  <style>
    .container {
      background: black;
      color: blanchedalmond;
    }
    .question_container{
      width: 100%;
    }
    .display{
      border-radius: 1em;
      box-shadow: 0px 2px 15px 2px #a26d28;
    }
    .header_block{
      margin-bottom: 2rem;
      margin-top: 1rem;
    }
    .width_margin{
      width: 80%;
      margin: 0 auto;
      text-align: center;
      margin-bottom: 1.5rem;
      margin-top: 1.5rem;
      padding: 1rem;
    }
    .flex_container{
      display: flex;
      flex-direction: column;
    }
    .content_body {
      width: 90%;
      display: flex;
      flex-direction: column;
      margin: 0 auto;
      padding: 1rem;
    }
    .question {
      background: rgba(255, 2555, 255, 0.1);
      padding: 1em;
      margin: 1em;
      border-radius: 1em;
    }
    .title {
      color: burlywood;
      font-size: 1.1em;

    }
    pre{
      color: #fff !important;
    }
    .algorithms{

        white-space: pre;
        text-align: left;
        background-color: rgba(255, 255, 255, 0.1);
        border-radius: 1em;
        padding: 1rem;
        
    }
    .algorithms code{
      color: #fff;

    }
    @media only screen and (max-width: 480px){
      code{
        font-size: 0.8em;
        white-space: pre;
        text-align: left;
        overflow-x: scroll;
      }
      .algorithms{
        font-size: 0.46em;
        white-space: pre;
        text-align: left;
        overflow-x: scroll;
      }

    }
    @media only screen and (max-width: 290px){
      .algorithms{
        font-size: 0.4em;
        white-space: pre;
        text-align: left;
      } 
    }
  </style>

  {% block title %}
  <title>Algorithms</title>
  {% endblock %}
</head>
<div class="content_body">
  <h2 align="center" class="header_block">
    The Algorithms to fetch the Passcode are
  </h2>

  
    <div class="question_container flex_container">
      {% for question in questions %}
        <div class="width_margin display">
          <p style="white-space: nowrap;"><h3 class="title">{{ question.level}}. {{ question.title }}</h3></p>
          <p>{{ question.description}}</p>
          <br>
          <p class="algorithms">{{ question.algo|safe}}</p>
          <br>
          <button class="btn" style="margin:0 auto;"><a href="{% url 'quiz:showanswer' question.id %}" >Check Answer</a></button>
        </div>
      {% endfor %}
    </div>
  

  
</div>

{% endblock %}

quiz/templates/quiz/answerdisplay.html
{% extends 'base.html'%} {% load static %} {% block content %}
<head>
  <link rel="stylesheet" href="{% static 'quiz/quiz.css' %}" />
  <style>
    .container {
      background: black;
      color: blanchedalmond;
    }
    .content {
      pointer-events: none;
      cursor: not-allowed;
      flex-direction: column;
    }
    .htit {
      margin-top: 1em;
      margin-bottom: 1em;
    }
    .question {
      background: rgba(255, 2555, 255, 0.1);
      padding: 1em;
      margin: 1em;
      border-radius: 1em;
    }
    .title {
      color: burlywood;
    }
    code{
      white-space: pre;
    }
    pre{
      color: #fff !important;
    }
    .algorithms{

        white-space: pre;
        text-align: left;
        background-color: rgba(255, 255, 255, 0.1);
        border-radius: 1em;
        padding: 1rem;
        
    }
    .algorithms code{
      color: #fff;

    }
    @media only screen and (max-width: 480px){
      code{
        font-size: 0.8em;
        white-space: pre;
        text-align: left;
        overflow-x: scroll;
      }
      .algorithms{
        font-size: 0.46em;
        white-space: pre;
        text-align: left;
        overflow-x: scroll;
      }

    }
    @media only screen and (max-width: 290px){
      .algorithms{
        font-size: 0.4em;
        white-space: pre;
        text-align: left;
      } 
    }
  </style>
  {% block title %}
    <title>Question Answer</title>
  {% endblock %}
</head>


<div class="content">
  <div class="stage1">
    <div class="context">
      <ul>
        <li>Question Level : {{ question.level}}</li>

        <li class="title">
          Question Title : {{ question.title }}
        </li>

        <li>
          <p class="question">
            {{question.description}}
          </p>
          <br />
        </li>

        <li style="color: #fff;">
          <p>Algorithm :</p>
          <p class="algorithm" style="color: #fff;">
            {{ question.algo|safe}}
          </p>
        </li>

        <li>
          <p class="question">
            In case you forgot
            <br />
            Answer : <font color="#a26d2"> {{question.answer}}</font>
          </p>
        </li>
        <br />
      </ul>
    </div>
  </div>
  <br />

</div>

{% endblock %}

quiz/templates/quiz/end.html
{% extends 'base.html'%} {% load static %} {% block content %}
<head>
  <link rel="stylesheet" href="{% static 'quiz/quiz.css' %}" />
  {% block title %}
  <title>PASSCODE</title>
  {% endblock %}
</head>

<div class="content">
  <div class="stage1">
    Thanks for Playing with US. <br />
    You have completed Stage 1. <br />
    Enter the PASSCODE for BONUS points. 
    <div>
      <form action="{% url 'quiz:algo'%}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn">
         Algorithms
        </button>
      </form>
    </div>
  </div>

  {% if check %}
  <p class="wrong">
    please try again,
    <br />
    your answer was incorrect
  </p>
  {% endif %}

  <form action="{% url 'quiz:algo'%}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn">
      Algorithms
    </button>
  </form>
  <div class="stage1">
    <form action="{% url 'quiz:passcode' %}" method="POST">
      {% csrf_token %}
      <h1>
        Enter The passcode below
      </h1>
      {{form.as_p}}
      <button class="btn btn-primary mb1 bg-blue" type="submit">
        Submit
      </button>
    </form>
  </div>
</div>

{% endblock %}

quiz/templates/quiz/finish.html
{% extends 'base.html'%} {% load static %} {% block content %}

<head>
  <link rel="stylesheet" href="{% static 'quiz/finish.css' %}" />
  <style>
    .circle img {
      height: 30vh;
      width: 30vh;
    }

    .congrate {
      text-align: center;
    }
  </style>
  {% block title %}
  <title>Congrats!</title>
  {% endblock %}
</head>

<div class="content">
  '
  <div class="circle">
    <img src="{% static 'quiz/WHEEL2.png'%}" alt="wheel" />
  </div>
  <div class="stage1">
    <div class="congrate">
      Congratulations !!
      <br />
      You have finished the Mission.
    </div>
    <br />

    <h3>
      Visit
    </h3>
    <a href="{% url 'user:dashboard'%}">
      <button class="btn btn-primary mb1 bg-blue">
        Dashboard
      </button>
    </a>
    <a href="{% url 'user:leaderboard'%}">
      <button class="btn btn-primary mb1 bg-blue">
        Leaderboard
      </button>
    </a>
  </div>
</div>

{% endblock %}

quiz/templates/quiz/index.html
{% extends 'base.html'%} {% load static %} {% block content %}

<head>
  <link rel="stylesheet" href="{% static 'quiz/quiz.css' %}" />
  <style>
    img {
      max-height: 30vh;
    }

    .content {
      justify-content: center;
    }

    .questions {
      display: flex;
      flex-flow: row wrap;
    }
    .number {
      color: #d29d28;
    }
    .number,
    .title {
      padding: 0.5em;
    }
    .title a:hover {
      color: #9e9e9e;
    }

    .listQ {
      background-color: rgba(0, 0, 0, 0.85);
      padding: 0.3em;
      margin: 0.5em;
      max-width: 80vw;
      border-radius: 1em;
      margin-top: 1em;
      box-shadow: 0px 2px 8px 2px #a26d28;
      justify-content: center;
      align-items: center;
    }

    .display_box,
    .listQ {
      max-width: 48%;
    }
    .stage2Q {
    }
    .coverQ {
      flex: 33%;
    }
    #countdownbcontainer {
      display: flex;
      flex-direction: column;
      color: #fff;
    }
    .message {
      display: block;
      padding: 1rem;
      margin: 1em;
      color: #fff;
      background: rgba(0, 0, 0, 0.85);
      box-shadow: 0px 2px 8px 2px #d99236;
      border-radius: 1em;
    }
    #countdownblock {
      background-color: rgba(0, 0, 0, 0.85);
      padding: 1em;
      margin: 0.5em;
      max-width: 80vw;
      border-radius: 1em;
      margin-top: 1em;
      box-shadow: 0px 2px 8px 2px #d99236;
      color: white;
      font-size: 2em;
      display: flex;
      align-items: center;
      justify-content: space-around;
      /* background-color: blanchedalmond; */
    }
    #countdownblock .cntdwn {
      text-align: center;
      padding: 1rem;
    }
    #countdownblock .cntdwn .text {
      font-size: 0.5em;
    }
    @media only screen and (max-width: 700px) {
      #countdownblock {
        font-size: 1em;
      }
    }
    @media only screen and (max-width: 300px) {
      #countdownblock {
        font-size: 0.6em;
      }
    }
    @media only screen and (max-width: 900px) {
      .coverQ {
        flex: 100%;
      }
      .display_box,
      .listQ {
        max-width: 80%;
        padding-top: 1rem;
        padding-bottom: 1rem;
        font-size: 0.8em;
      }
    }
  </style>
</head>

<div class="content">
  <br />
  <div class="display_box stage1">
    <h4 align="center">
      Congratulations {{player.name }} <br />
      on reaching Stage 2!
    </h4>
    <br />
    <img src="{{player.image}}" alt="{{ player.name }}" class="propic" />
    <br />
    <p align="center"></p>

    <p align="center">To view or answer a question click on its title</p>
    <br />
  </div>

  <div class="listQ">
    <h4 class="display">
      Till Now you have solved
      <br />
      {{player.count2}} question{{ player.count2|pluralize}} in Stage 2
    </h4>
    <div class="questions">
      {% for i in q %}
      <div class="coverQ">
        <div class="stage2Q">
          <div class="number">Question No. {{i.level}}</div>
          <div class="title">
            <a href="{% url 'quiz:individual' i.level %}"> {{ i.title }} </a>
          </div>
          <!-- <div class="description">
                      {{i.description}}
                    </div> -->
          {% if i.image %}
          <div class="image">
            <img src="{{i.image}}" alt="{{i.title}}" />
          </div>
          {% endif %}
        </div>
        {% if i.files%}
        <div class="files">
          <audio src="{{i.files.url}}" controls></audio>
        </div>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<div class="countdownbcontainer">
  <div id="countdownblock" class="">
    <div class="cntdwn">
      <p id="days"></p>
      <p class="text">days</p>
    </div>
    <p>:</p>
    <div class="cntdwn">
      <p id="hours"></p>
      <p class="text">hours</p>
    </div>
    <p>:</p>
    <div class="cntdwn">
      <p id="mins"></p>
      <p class="text">minutes</p>
    </div>
    <p>:</p>
    <div class="cntdwn">
      <p id="seconds"></p>
      <p class="text">seconds</p>
    </div>
  </div>
  <div class="message">
    Congratulations on reaching Second round. The second round will start at
    9:00 AM, 13th Sept.
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
  // Set the date we're counting down to
  var countDownDate = new Date("Sep 13, 2020 9:00:00").getTime();

  // Update the count down every 1 second
  var x = setInterval(function () {
    // Get today's date and time
    var now = new Date().getTime();

    // Find the distance between now and the count down date
    var distance = countDownDate - now;

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor(
      (distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
    );
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    document.getElementById("days").innerHTML = days;
    document.getElementById("hours").innerHTML = hours;
    document.getElementById("mins").innerHTML = minutes;
    document.getElementById("seconds").innerHTML = seconds;

    // If the count down is over, go back to home
    if (distance < 0) {
      clearInterval(x);

      document.getElementById("countdownblock").innerHTML = "";
      $(".countdownbcontainer").css("display", "none");
      $(".content").css("display", "flex");
    } else {
      $(".countdownbcontainer").css("display", "flex");
      $(".content").css("display", "none");
    }
  });
</script>

{% endblock %}

quiz/templates/quiz/smart.html
{% extends 'base.html'%} {% load static %} {% block content %}

<head>
  {% block title %}
  <title>Bad Link</title>
  {% endblock %}
  <link rel="stylesheet" href="{% static 'quiz/quiz.css'%}" />
</head>

<div class="content">
  <p class="stage1">
    Looks like you followed a bad link

    <br />

    Page Not Found !!!
  </p>
</div>
{% endblock %}

quiz/templates/quiz/solved.html
{% extends 'base.html'%} {% load static %} {% block content %}

<head>
    <link rel="stylesheet" href="{% static 'quiz/quiz.css' %}" />
    {% block title %}
        <title>solved</title>
    {% endblock %}
</head>
<div class="content" >
    <p class="stage1" style="padding: 1rem;">
        <span style="font-size: 1.3em;">  Hurrah! <br>   You have sucessfully solved this Question.</span>
        <br>
        <button class="btn" style="margin-top: 1rem;">
            <a  href="{% url 'quiz:index' %}" style="">
                Back to Questions Page
            </a>
        </button>
    </p>

</div>
{% endblock %}