Qriosity/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
import user
import home

urlpatterns = [
    path('harrypotter/', admin.site.urls),
    path('user/', include('user.urls')),
    path('quiz/', include('quiz.urls')),
    path('', include('home.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'


urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('rules/', views.rules, name="rules"),
    path('abadakadabra/qualifiedlist/', views.page, name="page"),
]

quiz/urls.py
from django.urls import path
from django.conf.urls import url,include
from . import views

app_name = 'quiz'


urlpatterns = [
    path('', views.StageOne, name='stageone'),
    path('answer/', views.Stage1Answer, name="answer"),
    path('hint/', views.Stage1Hint, name="hint"),
    path('stage2/', views.Index, name="index"),
    path('<int:qid>', views.Individual, name="individual"),
    path('passcode/', views.Passcode, name="passcode"),
    path('algo/', views.Algo, name="algo"),
    
    url(r'^algo/questions/(?P<pk>.*)/$',views.showanswer,name='showanswer'),
]

user/urls.py
from django.urls import path
from .import views

app_name = 'user'


urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('privacypolicy', views.privacy_policy_fb, name="privacypolicy"),
    path('details/', views.UserData, name="details"),
    path('form/', views.Formdata, name="formdata"),
    path('details/logout/', views.logout, name="logout"),
    path('story/', views.story, name="story"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
# Create your models here.


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=400)
    email = models.CharField(max_length=100, null=True, blank=True)
    image = models.CharField(max_length=200, blank=True)
    score = models.IntegerField(default=0)
    rank = models.IntegerField(default=0)
    last_submit = models.DateTimeField(
        default=datetime.utcnow()+timedelta(hours=5.5))
    question_level = models.IntegerField(default=1)
    level2 = models.IntegerField(default=-2)
    count2 = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class PlayerDetails(models.Model):
    user_name = models.OneToOneField(
        Player, on_delete=models.CASCADE, primary_key=True)
    full_name = models.CharField(default="your name", max_length=400)
    college = models.CharField(default="none", max_length=400)
    year = models.CharField(default="1", max_length=10)
    contact = models.BigIntegerField(default=1, blank=True)

    def __str__(self):
        return self.college


class Solved(models.Model):
    gamer = models.ForeignKey(Player, on_delete=models.CASCADE)
    level_on = models.IntegerField(default=0, blank=True)
    solved = models.BooleanField(default=False)


class StageOneHint(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    level = models.IntegerField(default=0, blank=True)
    taken = models.BooleanField(default=False)

user/forms.py
from django import forms


class UserDetails(forms.Form):
    full_name = forms.CharField(max_length=400, label="Enter Your Full Name")
    college = forms.CharField(max_length=400, label="Enter Your college name")
    year = forms.IntegerField(min_value=1, max_value=4,
                              label="Enter your studying year")
    contact = forms.CharField(
        min_length=10, max_length=10, label="Enter your Phone Number", required=False)

user/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.contrib.auth.decorators import login_required
from .import models
from datetime import datetime, timedelta
from .forms import UserDetails
# from django.contrib.auth.models import User

# Create your views here.

current_leaderboard = None


def logout(request):
    return render(request, 'user/logout.html')


@login_required(login_url='/login', redirect_field_name=None)
def dashboard(request):
    player = models.Player.objects.get(user=request.user)
    print("In dashboard - Name - {}  User - {}".format(player.name, player.user))
    cl = models.Player.objects.order_by(
        '-score', 'last_submit')
    j = 0

    # code for calaculating the dyanmic rank 
    # cl gives the scores in descending order 
    # we store the rank in j
    # variable naming is very bad XD

    for i in cl:
        j += 1
        if i.user == player.user:
            print(j)
            break


    # cl = models.Player.objects.filter(level2__gte=0).order_by(
    #     '-score', 'last_submit')
    # j = 0
    # for i in cl:
    #     j += 1
    #     if i.user == player.user:
    #         print(j)
    #         break
    # if player.level2 < 0:
    #     j = 0
    return render(request, 'user/dashboard.html', {'player': player, "rank": j})


#@login_required(login_url='/login', redirect_field_name=None)
def save_profile(backend, user, response, *args, **kwargs):
    if backend.name == 'google-oauth2':
        profile = user
        try:
            player = models.Player.objects.get(user=profile)
        except:
            player = models.Player(user=profile)
            player.last_submit = datetime.utcnow()+timedelta(hours=5.5)
            player.name = response.get('name')
            player.image = response.get('picture')
            player.email = response.get('email')
            player.save()
    elif backend.name == 'facebook':
        profile = user
        try:
            player = models.Player.objects.get(user=profile)
        except:
            player = models.Player(user=profile)
            player.name = response.get(
                'first_name')+" "+response.get('last_name')
            player.email = response.get('email')
            player.image = "http://graph.facebook.com/%s/picture?type=large" \
                % response["id"]
            player.last_submit = datetime.utcnow()+timedelta(hours=5.5)
            player.save()


@login_required(login_url='/login', redirect_field_name=None)
def leaderboard(request):
    global current_leaderboard

    current_leaderboard = models.Player.objects.order_by(
        '-score', 'last_submit')

    leader = models.Player.objects.order_by(
        '-score', 'last_submit')[:1]
    n = models.Player.objects.count()

    # uncomment when 2nd round in play
    # current_leaderboard = models.Player.objects.filter(level2__gte=0).order_by(
    #     '-score', 'last_submit')[:3]
    # leader = models.Player.objects.filter(level2__gte=0).order_by(
    #     '-score', 'last_submit')[:1]
    # n = models.Player.objects.filter(level2__gte=0).count()
    return render(request, 'user/leaderboard.html', {'leaderboard': current_leaderboard, 'leader': leader, 'n': n})


def privacy_policy_fb(request):
    return render(request, "user/privacypolicy.html")


@login_required(login_url='/login', redirect_field_name=None)
def UserData(request):
    my_form = UserDetails()
    context = {
        "form": my_form
    }
    return render(request, "user/details.html", context)


@login_required(login_url='/login', redirect_field_name=None)
def Formdata(request):
    if request.method == "POST":
        my_form = UserDetails(request.POST)
        if my_form.is_valid():
            # my form is valid
            form_data = my_form.cleaned_data
            p1 = models.Player.objects.get(user=request.user)
            r = models.PlayerDetails(
                user_name=p1, college=form_data['college'], year=form_data['year'], contact=form_data['contact'],
                full_name=form_data['full_name'])
            r.save()

        else:
            z = my_form.errors
            print(z)
    p1 = models.Player.objects.get(user=request.user)

    try:
        r = models.PlayerDetails.objects.get(user_name=p1)
        return render(request, 'user/form_status.html', {"details": r})
    except models.PlayerDetails.DoesNotExist:
        render(request, "user/details.html")

    my_form = UserDetails()
    context = {
        "form": my_form
    }
    return render(request, "user/details.html", context)


def story(request):
    return render(request, 'user/story.html')

user/templates/user/dashboard.html
{% extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'user/styles.css' %}" />
{% block title%} <title>Dashboard</title>{% endblock %}
<style>
  .imageusr {
    height: 20vh;
    width: 20vh;
  }
</style>
<div class="content">
  <div class="user">
    <img
      src="{{ player.image }}"
      alt="{{ player.name }}"
      class="imageusr"
    /><br />
    <div class="name" style="font-size: x-large; font-weight: 600;">
      {{ player.name }}
    </div>

    <div class="det_container">
      <div class="score" style="font-size: medium;">
        <p>{{ player.score }}</p>
        <p>Score</p>
      </div>
     <div class="rank" style="font-size: medium;">
      <p>{{rank}}</p>
      <p>Rank</p>

        <!-- {% if rank != 0 %}
           <p>{{rank}}</p>
           <p>Rank</p>
        {% else %}
           <p>NQ</p>
           <p>Rank</p>
       {% endif %} -->
      </div>
    </div>

    <form action="{% url 'quiz:stageone' %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary mb1 bg-blue">
        Start
      </button>
    </form>
    <br />
    <a href="{% url 'user:formdata' %}">
      <button
        style="font-size: medium;"
        type="submit"
        class="btn btn-primary mb1 bg-blue"
      >
        View/Update Profile
      </button></a
    >
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
<script>
  particlesJS.load(
    "particles-js",
    "{% static 'home/home.json' %}",
    function () {}
  );
</script>
{% endblock %}

user/templates/user/details.html
{%extends 'base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'user/forms.css' %}" />
<head>
  {% block title %}
  <title>Fill contact details</title>
  {% endblock %}
</head>
<div class="content usercontactblock">
  <form action="{% url 'user:formdata' %}" method="POST">
    <h2 align="center">
      Fill your details
    </h2>

    {% csrf_token %} {{ form.as_p }}

    <button type="submit" class="btn">
      Submit
    </button>
    <br />
  </form>
</div>

{% endblock %}

user/templates/user/form_status.html
{%extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'user/forms1.css' %}" />
<head>
  {% block title %}
  <title>Contact Info 📇</title>
  {% endblock %}
</head>
<div class="content">
  <br /><br />

  <div class="box">
    <h3>
      Your current Profile details :
    </h3>
    <br />
    <p>
      Name : {{details.full_name}}
    </p>
    <br />
    <p>
      College : {{details.college}}
    </p>
    <br />
    <p>
      Year : {{details.year}}
    </p>
    <br />
    <p>
      Contact Number : {{details.contact}}
    </p>
  </div>

  <div class="submit">
    <a href="{% url 'user:details'%}">
      <button value="Update Contact" class="btn btn-primary mb1 bg-blue">
        Update Profile
      </button>
    </a>
  </div>
  <div class="submit">
    <a href="{% url 'user:dashboard'%}">
      <button
        value="Update Contact"
        class="btn btn-primary mb1 bg-blue"
        style="font-size: medium;"
      >
        Proceed to Dashboard
      </button>
    </a>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
<script>
  particlesJS.load(
    "particles-js",
    "{% static 'home/home.json' %}",
    function () {
      console.log("Hello Qriosity Player !!!");
    }
  );
</script>
{% endblock %}

user/templates/user/leaderboard.html
{% load static %}
<html>

<head>
    <title>Leaderboard</title>
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Red+Hat+Display:400,900&display=swap" type="text/css" />
    <link rel="shortcut icon" href="{% static 'home/home.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'user/leaderboard.css' %}" />
    <style>

    </style>
</head>

<body>
    <header>
        <h1>
            <a class="qriosity" href="{% url 'home:home' %}">Qriosity 2.0</a>
        </h1>

        <nav>
            <ul>
                <li>
                    <a href="{% url 'home:rules'%}">Rules</a>
                </li>
                <li>
                    <a href="{% url 'user:leaderboard' %}"> LeaderBoard </a>
                </li>
                <li>
                    <a href="{% url 'quiz:stageone' %}">Arena</a>
                </li>
                <li>
                    <a href="{% url 'user:story' %}">Story</a>
                </li>
                <li>
                    <a href="{% url 'user:dashboard' %}"> Dashboard </a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
            </ul>
        </nav>
    </header>
    <div class="content">
        <div class="topper">
            {% for top in leader%}
            <img src="{{top.image}}" alt="{{top.name}}" class="tpic" />
            <h3 class="thname">
                {{top.name}}
            </h3>
            <h3 class="tscore">
                {{top.score}}
            </h3>
            {% endfor %}
        </div>
        <div class="box">
            <br />
            <div class="search">
                <input type="text" id="searchbox" placeholder="Search Your Name Here ...." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Your Name Here ....'" />
                <br />
            </div>
            <div class="list">
                <br /> {% for player in leaderboard %}
                <div class="item">
                    <div style="position: relative;">
                    <div class="pic" style="background-image: url({{ player.image }});"></div></div>
                    <!--<div class="player_details">-->
                        <div class="name">
                            {{ player.name }}
                        </div>
                        <div class="score">
                            {{ player.score }}
                        </div>
                    <!--</div>-->
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br /><br /><br /><br /><br />
    <div class="newline"><br /><br /><br /></div>
    {% include 'partials/_footer.html'%}

    <!-- <div class="parallax"></div> -->

    <script type="text/javascript">
        var no = "{{n}}";
        console.log(no);
        $(document).ready(function() {
            $("#searchbox").on("keyup", function() {
                for (i = 0; i < no; i++) {
                    let inp = document.querySelector("#searchbox").value;
                    let msg = document.querySelector(".searchResult");
                    let org = document.querySelectorAll(".item")[i];
                    if (
                        org
                        .querySelector(".name")
                        .innerText.toUpperCase()
                        .indexOf(inp.toUpperCase()) > -1
                    ) {
                        org.style.display = "";
                    } else {
                        org.style.display = "none";
                    }
                }
            });
        });

        function myFunction() {
            var x = document.getElementById("myLinks");
            if (x.style.display === "block") {
                x.style.display = "none";
            } else {
                x.style.display = "block";
            }
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function (){
            var body_height = $('body').height();
            var header_height = $('header').height();
            var footer_height = $('footer').height();
            var box_height =(body_height-(header_height+footer_height)-20-32);

            if(window.matchMedia("(max-width: 980px)").matches){
               var topper_height = $('.topper').outerHeight(); 
               box_height = box_height - topper_height-32+16;
            }
            $('.content .box').css("height",box_height+"px");
        })
    </script>
</body>

</html>

user/templates/user/logout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{% static 'home/home.ico' %}"
      type="image/x-icon"
    />

    <title>Logged Out !</title>
  </head>

  <body>
    <div class="header">
      <nav>
        Navbar & Heading
      </nav>
    </div>

    <div class="container">
      <h4>Login to view this page</h4>
    </div>
  </body>
</html>

user/templates/user/privacypolicy.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Privacy Policy</title>
</head>

<body>
    <h1>Privacy Policy for IEEE SB NIT DURGAPUR</h1>

    <p>
        At Qriosity, accessible from http://qriosity2.ieeesbnitdgp.com/, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Qriosity and how we use it.
    </p>

    <p>
        If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.
    </p>

    <p>
        This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Qriosity. This policy is not applicable to any information collected offline or via channels
        other than this website.
    </p>

    <h2>Consent</h2>

    <p>
        By using our website, you hereby consent to our Privacy Policy and agree to its terms.
    </p>

    <h2>Information we collect</h2>

    <p>
        The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.
    </p>
    <p>
        If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.
    </p>
    <p>
        When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.
    </p>

    <h2>How we use your information</h2>

    <p>We use the information we collect in various ways, including to:</p>

    <ul>
        <li>Provide, operate, and maintain our webste</li>
        <li>Improve, personalize, and expand our webste</li>
        <li>Understand and analyze how you use our webste</li>
        <li>Develop new products, services, features, and functionality</li>
        <li>
            Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the webste, and for marketing and promotional purposes
        </li>
        <li>Send you emails</li>
        <li>Find and prevent fraud</li>
    </ul>

    <h2>Log Files</h2>

    <p>
        Qriosity follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP)
        addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is
        for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information. Our Privacy Policy was created with the help of the
        <a href="https://www.privacypolicygenerator.info">Privacy Policy Generator</a
      >
      and the
      <a href="https://www.privacypolicytemplate.net/"
        >Privacy Policy Template</a
      >.
    </p>

    <h2>Cookies and Web Beacons</h2>

    <p>
      Like any other website, Qriosity uses 'cookies'. These cookies are used to
      store information including visitors' preferences, and the pages on the
      website that the visitor accessed or visited. The information is used to
      optimize the users' experience by customizing our web page content based
      on visitors' browser type and/or other information.
    </p>

    <p>
      For more general information on cookies, please read
      <a href="https://www.cookieconsent.com/what-are-cookies/"
        >"What Are Cookies"</a
      >.
    </p>

    <h2>Advertising Partners Privacy Policies</h2>

    <p>
      You may consult this list to find the Privacy Policy for each of the
      advertising partners of Qriosity.
    </p>

    <p>
      Third-party ad servers or ad networks uses technologies like cookies,
      JavaScript, or Web Beacons that are used in their respective
      advertisements and links that appear on Qriosity, which are sent directly
      to users' browser. They automatically receive your IP address when this
      occurs. These technologies are used to measure the effectiveness of their
      advertising campaigns and/or to personalize the advertising content that
      you see on websites that you visit.
    </p>

    <p>
      Note that Qriosity has no access to or control over these cookies that are
      used by third-party advertisers.
    </p>

    <h2>Third Party Privacy Policies</h2>

    <p>
      Qriosity's Privacy Policy does not apply to other advertisers or websites.
      Thus, we are advising you to consult the respective Privacy Policies of
      these third-party ad servers for more detailed information. It may include
      their practices and instructions about how to opt-out of certain options.
      You may find a complete list of these Privacy Policies and their links
      here: Privacy Policy Links.
    </p>

    <p>
      You can choose to disable cookies through your individual browser options.
      To know more detailed information about cookie management with specific
      web browsers, it can be found at the browsers' respective websites. What
      Are Cookies?
    </p>

    <h2>CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>

    <p>
      Under the CCPA, among other rights, California consumers have the right
      to:
    </p>
    <p>
      Request that a business that collects a consumer's personal data disclose
      the categories and specific pieces of personal data that a business has
      collected about consumers.
    </p>
    <p>
      Request that a business delete any personal data about the consumer that a
      business has collected.
    </p>
    <p>
      Request that a business that sells a consumer's personal data, not sell
      the consumer's personal data.
    </p>
    <p>
      If you make a request, we have one month to respond to you. If you would
      like to exercise any of these rights, please contact us.
    </p>

    <h2>GDPR Data Protection Rights</h2>

    <p>
      We would like to make sure you are fully aware of all of your data
      protection rights. Every user is entitled to the following:
    </p>
    <p>
      The right to access – You have the right to request copies of your
      personal data. We may charge you a small fee for this service.
    </p>
    <p>
      The right to rectification – You have the right to request that we correct
      any information you believe is inaccurate. You also have the right to
      request that we complete the information you believe is incomplete.
    </p>
    <p>
      The right to erasure – You have the right to request that we erase your
      personal data, under certain conditions.
    </p>
    <p>
      The right to restrict processing – You have the right to request that we
      restrict the processing of your personal data, under certain conditions.
    </p>
    <p>
      The right to object to processing – You have the right to object to our
      processing of your personal data, under certain conditions.
    </p>
    <p>
      The right to data portability – You have the right to request that we
      transfer the data that we have collected to another organization, or
      directly to you, under certain conditions.
    </p>
    <p>
      If you make a request, we have one month to respond to you. If you would
      like to exercise any of these rights, please contact us.
    </p>

    <h2>Children's Information</h2>

    <p>
      Another part of our priority is adding protection for children while using
      the internet. We encourage parents and guardians to observe, participate
      in, and/or monitor and guide their online activity.
    </p>

    <p>
      Qriosity does not knowingly collect any Personal Identifiable Information
      from children under the age of 13. If you think that your child provided
      this kind of information on our website, we strongly encourage you to
      contact us immediately and we will do our best efforts to promptly remove
      such information from our records.
    </p>
  </body>
</html>

user/templates/user/story.html
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
  <link rel="stylesheet" href="{% static 'user/story2.css' %}" />
  {% block title %}
  <title>Story</title>
  {% endblock %}
</head>

<div class="content">
  <p>
    In an alternate universe, the Second World War is happening. In our world,
    millions of lives were saved after Alan Turing cracked the cipher and the
    plans of Germans were foiled, which played a major part in the defeat of the
    Axis powers.
  </p>
  <p>
    A war is going on between the Allies and the Axis. For the rest of the
    world, they had to choose sides and enter the war. Thousands of people were
    dying every day. Axis powers were dominating the Allies, and most of their
    secrets travelled via radio signals which could be tracked by even a
    standard receiver, but what made the messages unreadable for non-Axis powers
    was the encryption. 159 quintillion combinations were possible in the
    cipher, and the combinations changed at the stroke of midnight every day.
    Allies could not afford to lose more of their citizens or soldiers. Like in
    our universe, there was a young man, a mathematician, at Cambridge
    University, who was interested to crack the cipher, not only because he
    wanted to help the Allies win the war, but because he loved solving puzzles.
    After getting his appointment letter, he joins the team and starts working
    on the machine that could decipher the codes sent by the Germans to know
    their plans. But Alan is not able to crack the encryption system. Now the
    onus falls upon us to help Alan Turing decipher the cipher and defeat the
    Axis powers. Are you up to the task at hand?
  </p>
  <p>
    Will you be able to help Alan Turing and lead the Allies to victory in this
    alternate universe?
  </p>
  <form action="{% url 'quiz:stageone' %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn">
      Start
    </button>
  </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
<script>
  particlesJS.load(
    "particles-js",
    "{% static 'user/particles.json' %}",
    function () {
      console.log("Hello Qriosity Player !!!");
    }
  );
</script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
  integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
  crossorigin="anonymous"
></script>
<script>
  // const height = $("br").next().position().top - $("br").position().top;
  calculated_height = $(".container").height();
  $("#particles-js").css("height", calculated_height);
  $(".particles-js-canvas-el").css("min-height", calculated_height);

  // console.log(height);
</script>
{% endblock %}